spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone =Asia/Shanghai
    username: root
    password: zhanghongyi123
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  mvc:
    static-path-pattern: /static/**


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  config-location: classpath:configure/mybatis-configure.xml
  mapper-locations: classpath:com.bookstore.bookstore_two.Mapper/*.xml
