spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone =Asia/Shanghai
    username: root
    password: zhanghongyi123
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis:
##  config-location: classpath:configure/mybatis-configure.xml
#
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:com.bookstore.bookstore_two.Mapper/*.xml
#  type-aliases-package: bean

mybatis-plus:
#  config-location: classpath:configure/mybatis-configure.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: bean
  global-config:
    db-config:
      table-prefix: t_